/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as FranchiseRouteImport } from './routes/franchise'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as StoryRouteImport } from './routes/story'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseRoute = FranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/founders': typeof FoundersRoute
  '/franchise': typeof FranchiseRoute
  '/menu': typeof MenuRoute
  '/story': typeof StoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/founders': typeof FoundersRoute
  '/franchise': typeof FranchiseRoute
  '/menu': typeof MenuRoute
  '/story': typeof StoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/founders': typeof FoundersRoute
  '/franchise': typeof FranchiseRoute
  '/menu': typeof MenuRoute
  '/story': typeof StoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/founders' | '/franchise' | '/menu' | '/story'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/founders' | '/franchise' | '/menu' | '/story'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/founders'
    | '/franchise'
    | '/menu'
    | '/story'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FoundersRoute: typeof FoundersRoute
  FranchiseRoute: typeof FranchiseRoute
  MenuRoute: typeof MenuRoute
  StoryRoute: typeof StoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise': {
      id: '/franchise'
      path: '/franchise'
      fullPath: '/franchise'
      preLoaderRoute: typeof FranchiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FoundersRoute: FoundersRoute,
  FranchiseRoute: FranchiseRoute,
  MenuRoute: MenuRoute,
  StoryRoute: StoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
